export enum Countries {
  Argentina = "Argentina",
  Austria = "Austria",
  Belgium = "Belgium",
  Brazil = "Brazil",
  Canada = "Canada",
  Denmark = "Denmark",
  Finland = "Finland",
  France = "France",
  Germany = "Germany",
  Ireland = "Ireland",
  Italy = "Italy",
  Mexico = "Mexico",
  Norway = "Norway",
  Poland = "Poland",
  Portugal = "Portugal",
  Spain = "Spain",
  Sweden = "Sweden",
  Switzerland = "Switzerland",
  Uk = "UK",
  Usa = "USA",
  Venezuela = "Venezuela",
  Null = "NULL",
}

export enum Regions {
  Ak = "AK",
  Bc = "BC",
  CA = "CA",
  CoCork = "Co. Cork",
  Df = "DF",
  Essex = "Essex",
  ID = "Id",
  IsleOfWight = "Isle of Wight",
  Lara = "Lara",
  MT = "MT",
  Nm = "NM",
  NuevaEsparta = "Nueva Esparta",
  Or = "OR",
  Québec = "Québec",
  Rj = "RJ",
  SP = "SP",
  Táchira = "Táchira",
  Wa = "WA",
  Wy = "WY",
  Null = "NULL",
}
